name: Android CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
    tags-ignore:
      - '**'
  pull_request:
    branches: [ '**' ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Setup JDK
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
      with:
        distribution: 'zulu'
        java-version: 17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 # v4.3.1
      with:
        gradle-home-cache-cleanup: true

    - name: Copy CI gradle.properties
      run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

    - name: Check build-logic
      run: ../gradlew :convention:check
      working-directory: ./build-logic

    - name: Build main project
      run: ./gradlew assembleDebug

    - name: Reformat main project
      run: ./gradlew spotlessCheck

    - name: Reformat build-logic
      run: ../gradlew spotlessCheck
      working-directory: ./build-logic

    - name: Run unit tests
      run: ./gradlew testDebugUnitTest

    - name: Run screenshot tests
      run: ./gradlew verifyRoborazziDebug
