name: Android CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
    tags-ignore:
      - '**'
  pull_request:
    branches: [ '**' ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: 17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-home-cache-cleanup: true

    - name: Copy CI gradle.properties
      run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

    - name: Check build-logic
      run: ../gradlew :convention:check
      working-directory: ./build-logic

    - name: Build projects
      run: ./gradlew assembleDebug

    - name: Run ktlint for main project
      run: ./gradlew spotlessCheck

    - name:  Run ktlint for build-logic
      run: ../gradlew spotlessCheck

    - name: Run unit tests
      run: ./gradlew testDebugUnitTest

    - name: Run screenshot tests
      run: ./gradlew verifyRoborazziDebug
