name: Android CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
    tags-ignore:
      - '**'
  pull_request:
    branches: [ '**' ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Setup JDK
      uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
      with:
        distribution: 'zulu'
        java-version: 17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4.4.1
      with:
        gradle-home-cache-cleanup: true

    - name: Copy CI gradle.properties
      run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

    - name: Check build-logic
      run: ../gradlew :convention:check
      working-directory: ./build-logic

    - name: Build main project
      run: ./gradlew assembleDebug

    - name: Reformat main project
      run: ./gradlew spotlessCheck

    - name: Reformat build-logic
      run: ../gradlew spotlessCheck
      working-directory: ./build-logic

    - name: Run unit tests
      run: ./gradlew testDebugUnitTest

    - name: Run screenshot tests
      run: ./gradlew verifyRoborazziDebug
