name: Fixup

on:
  workflow_dispatch:

jobs:
  fixes:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup JDK
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4.4.2
        with:
          gradle-home-cache-cleanup: true

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Reformat main project
        run: ./gradlew --continue spotlessApply

      - name: Reformat build-logic
        run: ../gradlew --continue spotlessApply
        working-directory: ./build-logic

      - name: Reformat Gradle plugin
        run: ./gradlew --continue spotlessApply
        working-directory: ./gradle-plugin

      - name: Push reformatted code
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6.0.1
        with:
          file_pattern: '**/*.kt **/*.gradle.kts'
          disable_globbing: true
          commit_message: "🤖 reformat"

      - name: Repair screenshots
        run: ./gradlew --continue verifyAndRecordRoborazziDebug

      - name: Push new screenshots if available
        uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6.0.1
        if: ${{ always() }}
        with:
          file_pattern: '**/screenshots/*.png'
          disable_globbing: true
          commit_message: "🤖 Updates screenshots"
