name: Fixup

on:
  workflow_dispatch:

jobs:
  fixes:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup JDK
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b # v4.3.0
        with:
          gradle-home-cache-cleanup: true

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Reformat main project
        run: ./gradlew --continue spotlessApply

      - name: Reformat build-logic
        run: ../gradlew --continue spotlessApply
        working-directory: ./build-logic

      - name: Reformat Gradle plugin
        run: ./gradlew --continue spotlessApply
        working-directory: ./gradle-plugin

      - name: Push reformatted code
        uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79 # v5.1.0
        with:
          file_pattern: '**/*.kt **/*.gradle.kts'
          disable_globbing: true
          commit_message: "🤖 reformat"

      - name: Repair screenshots
        run: ./gradlew --continue verifyAndRecordRoborazziDebug

      - name: Push new screenshots if available
        uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79 # v5.1.0
        if: ${{ always() }}
        with:
          file_pattern: '**/screenshots/*.png'
          disable_globbing: true
          commit_message: "🤖 Updates screenshots"
