name: Fixup

on:
  workflow_dispatch:

jobs:
  fixes:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup JDK
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 # v4.3.1
        with:
          gradle-home-cache-cleanup: true

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Reformat main project
        run: ./gradlew --continue spotlessApply

      - name: Reformat build-logic
        run: ../gradlew --continue spotlessApply
        working-directory: ./build-logic

      - name: Reformat Gradle plugin
        run: ./gradlew --continue spotlessApply
        working-directory: ./gradle-plugin

      - name: Push reformatted code
        uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79 # v5.1.0
        with:
          file_pattern: '**/*.kt **/*.gradle.kts'
          disable_globbing: true
          commit_message: "🤖 reformat"

      - name: Repair screenshots
        run: ./gradlew --continue verifyAndRecordRoborazziDebug

      - name: Push new screenshots if available
        uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79 # v5.1.0
        if: ${{ always() }}
        with:
          file_pattern: '**/screenshots/*.png'
          disable_globbing: true
          commit_message: "🤖 Updates screenshots"
